apiVersion: v1
kind: Secret
metadata:
  name: weather-app-secret
type: Opaque
data:
  # Replace 'your-base64-encoded-api-key' with your actual WeatherAPI.com API key encoded in base64
  # To encode: echo -n "your-api-key" | base64
  api-key: your-base64-encoded-api-key